name: Release

on:
  workflow_dispatch: {}

  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
          always-auth: true

      - name: Install dependencies
        working-directory: radix-engine-toolkit
        run: yarn
      - name: Build
        working-directory: radix-engine-toolkit
        run: yarn run build
      - name: Release
        working-directory: radix-engine-toolkit
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn publish --verbose
      
      - name: Install dependencies
        working-directory: radix-engine-toolkit-lts
        run: yarn
      - name: Build
        working-directory: radix-engine-toolkit-lts
        run: yarn run build
      - name: Release
        working-directory: radix-engine-toolkit-lts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn publish --verbose
